### ISSUE TITLE
[Linker] [T6] Some weapon files within mod aren't being linked correctly

### ISSUE THREAD

**Issue by Jbleezy** [Laupetin/OpenAssetTools#103]
If you link `bowie_knife_zm` from `zm_buried.ff`, it works fine. However, if you take that same weapon file from the unlinker and add it to your mod folder with no changes made to the weapon file and link with that weapon file, the viewmodel for that weapon does not show.

I also noticed a few other weapons were not showing the weapon name when trying to override them on a Plutonium dedi if they were also linked from your mod even though I didn't see any noticeable issues with the weapons, so they are probably also not linking correctly: `insas_mp`, `vector_mp`, `sig556_mp`

**Comment by Laupetin** [comment]
For clarification:

> OAT build from original fastfile - works
OAT build from mod - doesn't work
Plutonium raw weapon override - works

**Comment by Laupetin** [comment]
The issue with the bowie knife should be solved now after #108 was merged.
The problem was that OAT did not correctly make a distinction between an empty string and a non-existing string (nullptr).

In the case of hideTags this made the game believe that it is supposed to hide a bone with the name "" (so an empty string).
The bowie knife model has exactly one bone with has an empty string as its name.

This is now fixed, OAT now handles an empty string as "no string", which is how the game does it as well.

I did not test the other weapons you listed but i suppose those must have had the same problem
