### ISSUE TITLE
[unlinker] t6 zones wont dump

### ISSUE THREAD

**Issue by switchuwu** [Laupetin/OpenAssetTools#266]
no matter what i do, oat just outputs "0 SearchPaths" on t6 zones. this doesnt happen on any other game's zones, only t6.
![image](https://github.com/user-attachments/assets/f362f283-24cd-42a2-9401-2b97bc545b0c)

**Comment by Laupetin** [comment]
Can you maybe give me a few more details?
- What is the version of OAT you are using? `Unlinker --version`
- Does this happen on all ff files? 
- Does copying the fastfile to the same folder as Unlinker (D:/cod modding/oat/OpenAssetTools) and doing `Unlinker ./weapons.ff`  work?

**Comment by switchuwu** [comment]
![image](https://github.com/user-attachments/assets/56b90867-7876-4626-9c82-ae9ce7414e6e)
![image](https://github.com/user-attachments/assets/358ca0ad-3090-449b-bb09-98039064c4db)
![image](https://github.com/user-attachments/assets/7e70173e-5fe1-4412-b035-f17e5b6707a5)
it happens on all files

**Comment by Laupetin** [comment]
I cannot replicate your problem unfortunately. I tried the exact same command in the same folder structure but it works fine for me.
My zm_buried.ff has the following hash, in case yours differs:
SHA256: 3DAB5FEC484415B9D72098A581FA9CF59A5407612DC21B8BD89CC32BFD634E81

The only way i can really debug this is when you have a `Unlinker.dmp` file in `%localappdata%\CrashDumps`, after you ran the command.
If you have, feel free to send it to me (best on Discord -> `@laupetin`),

**Comment by Laupetin** [comment]
@switchuwu 
Can you also make sure you have the latest Visual C++ Redistributables installed on your machine?
You can download them from here: https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#latest-microsoft-visual-c-redistributable-version

First try to install [the x64 version](https://aka.ms/vs/17/release/vc_redist.x64.exe) since you most likely have 64bit machine.
If that does not work, please try to additionally install [the x86 ones](https://aka.ms/vs/17/release/vc_redist.x86.exe). The links are taken from the page i linked.

If any of that fixed your problem, please let me know :)

**Comment by switchuwu** [comment]
the above solution worked
