### ISSUE TITLE
[Linker] Muzzle flash assets aren't automatically copied from a loaded zone for weapons

### ISSUE THREAD

**Issue by JezuzLizard** [Laupetin/OpenAssetTools#39]
There are two muzzle flash fx assets for a weapon; first person, and third person, and currently they are not automatically copied over as a dependency which causes the game to fill in the missing asset with a random asset.

**Comment by Laupetin** [comment]
I tried to add an MP weapon to Zombies now and encountered the same thing.
To clearify what exactly is happening though: The muzzle flash FX _are_ being automatically copied over into the new fastfile.
What is not automatically added to the new fastfile though is FX that are referenced by this FX.

An FxElemDef can reference other FxEffectDefs in a lot of places.
This referencing is done in the form of a string that is then looked up via `FindXAssetHeader` upon loading the fastfile.
Since OAT does not automatically detect strings with the names of assets as a reference to another asset, these referenced FXs are not copied.
Ingame this apparently leads to the game display _random FX_ for some reason i did not investigate.

To solve this there should be a mechanism that postprocesses an asset after loading to load assets that are just referenced by string.
Examples for this are FX in FX via `FxEffectDefRef` but also anims in weapons.
This adding of a dependency should only load the asset if it is not ignored since adding a forward referencing asset is not required in this case.
